#!/usr/bin/env python3
"""Emit Mermaid from orbitron.ac: physical AC3D tree and optional logical assemblies.

Physical tree: OBJECT / kids (usually flat under world). Logical tree: nested
subgraphs from orbitron_logical_assemblies.json (mesh names must match .ac).
"""
from __future__ import annotations

import argparse
import html
import json
import re
import sys
import xml.etree.ElementTree as ET
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any


@dataclass
class ACNode:
    otype: str
    name: str
    children: list[ACNode] = field(default_factory=list)


def _parse_name_line(line: str) -> str | None:
    m = re.match(r'name "([^"]*)"', line)
    return m.group(1) if m else None


def read_ac_object(lines: list[str], start: int) -> tuple[ACNode, int]:
    if start >= len(lines) or not lines[start].startswith("OBJECT "):
        raise ValueError(f"Expected OBJECT at line {start + 1}, got {lines[start]!r}")

    otype = lines[start].split(None, 1)[1].strip()
    i = start + 1
    name = "(unnamed)"
    if i < len(lines) and lines[i].startswith("name "):
        parsed = _parse_name_line(lines[i])
        if parsed is not None:
            name = parsed
        i += 1

    kids = 0
    while i < len(lines):
        if lines[i].startswith("kids "):
            kids = int(lines[i].split()[1])
            i += 1
            break
        i += 1

    children: list[ACNode] = []
    for _ in range(kids):
        child, i = read_ac_object(lines, i)
        children.append(child)

    return ACNode(otype=otype, name=name, children=children), i


def find_first_object_line(lines: list[str]) -> int:
    for idx, line in enumerate(lines):
        if line.startswith("OBJECT "):
            return idx
    raise ValueError("No OBJECT record found (not a valid AC3D file?)")


def parse_ac(path: Path) -> ACNode:
    text = path.read_text(encoding="utf-8", errors="replace")
    lines = text.splitlines()
    root_at = find_first_object_line(lines)
    root, pos = read_ac_object(lines, root_at)
    if pos < len(lines):
        tail = lines[pos].strip()
        if tail.startswith("OBJECT"):
            sys.stderr.write(
                f"warning: trailing content after root tree at line {pos + 1}: {tail[:60]!r}\n"
            )
    return root


def collect_nodes_depth_first(root: ACNode) -> list[tuple[ACNode, ACNode | None]]:
    out: list[tuple[ACNode, ACNode | None]] = []

    def walk(n: ACNode, parent: ACNode | None) -> None:
        out.append((n, parent))
        for c in n.children:
            walk(c, n)

    walk(root, None)
    return out


def mermaid_escape_label(s: str) -> str:
    return s.replace('"', "#quot;")


def subgraph_title_html(title: str) -> str:
    """Bold subgraph title; escape for safe use inside Mermaid/HTML label."""
    return f"<b>{html.escape(title, quote=True)}</b>"


# Alternating fill by nesting depth (odd = warm, even = cool) for subgraph containers.
_SUBGRAPH_FILL_ODD = "#FFF8E1"
_SUBGRAPH_FILL_EVEN = "#E3F2FD"
_SUBGRAPH_STROKE_ODD = "#6D4C41"
_SUBGRAPH_STROKE_EVEN = "#1565C0"


def emit_mermaid_physical(root: ACNode, ac_path: Path, xml_note: str | None) -> str:
    rows: list[str] = []
    rows.append("%% Auto-generated by tools/orbitron_ac_hierarchy_mmd.py")
    rows.append(f'%% Source mesh: {ac_path.as_posix()}')
    rows.append("%% Physical AC3D OBJECT / kids tree (flat if Blender exported siblings only)")
    if xml_note:
        for line in xml_note.splitlines():
            rows.append(f"%% {line}")
    rows.append("flowchart TB")
    rows.append("  %% Same object names FlightGear uses for object-name picks")

    nodes_df = collect_nodes_depth_first(root)
    ids: dict[int, str] = {}
    for i, (node, _) in enumerate(nodes_df):
        ids[id(node)] = f"n{i}"

    for i, (node, _) in enumerate(nodes_df):
        nid = ids[id(node)]
        label = mermaid_escape_label(node.name)
        if node.otype and node.otype != "world":
            label = f"{label}<br/><small>{mermaid_escape_label(node.otype)}</small>"
        elif node.otype == "world":
            label = f"{label}<br/><small>world</small>"
        rows.append(f'  {nid}["{label}"]')

    for node, parent in nodes_df:
        if parent is None:
            continue
        rows.append(f"  {ids[id(parent)]} --> {ids[id(node)]}")

    return "\n".join(rows) + "\n"


def subgraph_id(key: str) -> str:
    s = re.sub(r"[^a-zA-Z0-9_]", "_", key)
    if not s:
        s = "group"
    return "g_" + s


def part_node_id(mesh_name: str) -> str:
    s = re.sub(r"[^a-zA-Z0-9_]", "_", mesh_name)
    if not s:
        s = "part"
    return "p_" + s


def load_assemblies_json(path: Path) -> dict[str, Any]:
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict) or "root" not in data or "groups" not in data:
        raise ValueError("assemblies JSON must have top-level keys 'root' and 'groups'")
    groups = data["groups"]
    if not isinstance(groups, dict):
        raise ValueError("'groups' must be an object")
    return data


def validate_assemblies(
    mesh_names: set[str],
    root_key: str,
    groups: dict[str, Any],
) -> None:
    if root_key not in groups:
        raise ValueError(f"root group {root_key!r} not found in groups")

    for key, spec in groups.items():
        if not isinstance(spec, dict):
            raise ValueError(f"group {key!r} must be an object")
        if "title" not in spec or not isinstance(spec["title"], str):
            raise ValueError(f"group {key!r} needs a string 'title'")
        for m in spec.get("members", []):
            if m not in groups:
                raise ValueError(f"group {key!r} references unknown member {m!r}")
        for p in spec.get("parts", []):
            if not isinstance(p, str):
                raise ValueError(f"group {key!r} has non-string part name")

    part_to_group: dict[str, str] = {}

    def visit(key: str, stack: set[str]) -> None:
        if key in stack:
            raise ValueError(f"cycle in assembly members involving {key!r}")
        stack.add(key)
        spec = groups[key]
        for m in spec.get("members", []):
            visit(m, stack)
        for p in spec.get("parts", []):
            if p in part_to_group:
                raise ValueError(
                    f"part {p!r} listed in both {part_to_group[p]!r} and {key!r}"
                )
            part_to_group[p] = key
        stack.remove(key)

    visit(root_key, set())

    missing = sorted(mesh_names - set(part_to_group))
    extra = sorted(set(part_to_group) - mesh_names)
    if missing:
        raise ValueError(
            "assemblies JSON does not cover all mesh objects: "
            + ", ".join(missing)
        )
    if extra:
        raise ValueError(
            "assemblies JSON references unknown mesh names: " + ", ".join(extra)
        )


def emit_logical_mermaid(
    data: dict[str, Any],
    ac_path: Path,
    assemblies_json: Path,
    xml_note: str | None,
) -> str:
    root_key = str(data["root"])
    groups: dict[str, Any] = data["groups"]

    lines: list[str] = []
    lines.append("%% Auto-generated by tools/orbitron_ac_hierarchy_mmd.py (logical view)")
    lines.append(f'%% Source mesh: {ac_path.as_posix()}')
    lines.append(f'%% Assembly map: {assemblies_json.as_posix()}')
    lines.append(
        "%% Nesting is engineering grouping only; AC file remains a flat sibling list under world."
    )
    if xml_note:
        for row in xml_note.splitlines():
            lines.append(f"%% {row}")
    lines.append("flowchart TB")

    subgraph_style_queue: list[tuple[str, int]] = []
    mesh_part_ids: list[str] = []

    def render_group(key: str, depth: int) -> None:
        pad = "  " * depth
        spec = groups[key]
        gid = subgraph_id(key)
        subgraph_style_queue.append((gid, depth))
        title = subgraph_title_html(str(spec["title"]))
        lines.append(f'{pad}subgraph {gid}["{title}"]')
        if depth == 1:
            lines.append(f"{pad}  direction TB")
        for mk in spec.get("members", []):
            render_group(str(mk), depth + 1)
        for pname in spec.get("parts", []):
            pid = part_node_id(str(pname))
            mesh_part_ids.append(pid)
            plab = mermaid_escape_label(str(pname))
            lines.append(f'{pad}  {pid}["{plab}<br/><small>mesh</small>"]')
        lines.append(f"{pad}end")

    render_group(root_key, 1)

    for gid, depth in subgraph_style_queue:
        fill = _SUBGRAPH_FILL_ODD if depth % 2 == 1 else _SUBGRAPH_FILL_EVEN
        stroke = _SUBGRAPH_STROKE_ODD if depth % 2 == 1 else _SUBGRAPH_STROKE_EVEN
        lines.append(
            f"  style {gid} fill:{fill},stroke:{stroke},stroke-width:2px,color:#1a1a1a"
        )

    if mesh_part_ids:
        lines.append(
            "  classDef meshNode fill:#EDE7F6,stroke:#5E35B1,stroke-width:1px,color:#222"
        )
        # Avoid one enormous `class` line (some renderers choke on very long lines).
        chunk = 12
        for i in range(0, len(mesh_part_ids), chunk):
            batch = ",".join(mesh_part_ids[i : i + chunk])
            lines.append(f"  class {batch} meshNode")

    return "\n".join(lines) + "\n"


def orbitron_xml_offsets_note(xml_path: Path | None) -> str | None:
    if xml_path is None or not xml_path.is_file():
        return None
    tree = ET.parse(xml_path)
    root = tree.getroot()
    path_el = root.find("path")
    mesh = path_el.text.strip() if path_el is not None and path_el.text else ""
    off = root.find("offsets")

    def _off(tag: str) -> str:
        if off is None:
            return ""
        el = off.find(tag)
        return el.text.strip() if el is not None and el.text else ""

    pitch_v = _off("pitch-deg")
    roll_v = _off("roll-deg")
    head_v = _off("heading-deg")
    xv = _off("x-m")
    yv = _off("y-m")
    zv = _off("z-m")
    note_lines = [
        f"Orbitron.xml mesh: {mesh}",
        f"offsets: pitch-deg={pitch_v!s} roll-deg={roll_v!s} heading-deg={head_v!s} "
        f"x-m={xv!s} y-m={yv!s} z-m={zv!s}",
    ]
    return "\n".join(note_lines)


def main() -> int:
    ap = argparse.ArgumentParser(description="AC3D parts tree → Mermaid flowchart(s)")
    ap.add_argument(
        "--ac",
        type=Path,
        default=Path("Aircraft/Orbitron-TestStand/Models/orbitron.ac"),
        help="Path to orbitron.ac",
    )
    ap.add_argument(
        "--orbitron-xml",
        type=Path,
        default=None,
        help="Optional Orbitron.xml for offset annotations in header comments",
    )
    ap.add_argument(
        "-o",
        "--out",
        type=Path,
        default=Path("Aircraft/Orbitron-TestStand/build/orbitron_ac_parts_hierarchy.mmd"),
        help="Output for physical AC tree (.mmd)",
    )
    ap.add_argument(
        "--assemblies-json",
        type=Path,
        default=None,
        help="orbitron_logical_assemblies.json (logical nested subgraphs)",
    )
    ap.add_argument(
        "--logical-out",
        type=Path,
        default=None,
        help="Optional second .mmd for logical assembly diagram",
    )
    args = ap.parse_args()

    ac_path = args.ac.resolve()
    if not ac_path.is_file():
        print(f"error: AC file not found: {ac_path}", file=sys.stderr)
        return 1

    xml_path = args.orbitron_xml
    if xml_path is not None:
        xml_path = xml_path.resolve()
    else:
        guess = ac_path.parent / "Orbitron.xml"
        if guess.is_file():
            xml_path = guess

    root = parse_ac(ac_path)
    note = orbitron_xml_offsets_note(xml_path)
    physical = emit_mermaid_physical(root, ac_path, note)
    out_path = args.out.resolve()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(physical, encoding="utf-8")
    print(f"Wrote {out_path} ({len(root.children)} top-level objects under world)")

    logical_out = args.logical_out
    if logical_out is not None:
        aj = args.assemblies_json
        if aj is None:
            print("error: --logical-out requires --assemblies-json", file=sys.stderr)
            return 1
        aj = aj.resolve()
        if not aj.is_file():
            print(f"error: assemblies JSON not found: {aj}", file=sys.stderr)
            return 1
        mesh_names = {c.name for c in root.children}
        try:
            data = load_assemblies_json(aj)
            validate_assemblies(mesh_names, str(data["root"]), data["groups"])
        except (ValueError, json.JSONDecodeError) as e:
            print(f"error: {e}", file=sys.stderr)
            return 1
        logical = emit_logical_mermaid(data, ac_path, aj, note)
        logical_path = logical_out.resolve()
        logical_path.parent.mkdir(parents=True, exist_ok=True)
        logical_path.write_text(logical, encoding="utf-8")
        print(f"Wrote {logical_path} (logical assemblies)")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
